export const SET_ASSESSMENT_DATA = 'SET_ASSESSMENT_DATA';
export const RESET_ASSESSMENT_DATA = 'RESET_ASSESSMENT_DATA';
export const FETCH_ASSESSMENT_DATA = 'FETCH_ASSESSMENT_DATA';
export const SET_FINAL_SCORE = 'SET_FINAL_SCORE';
export const RESET_FINAL_SCORE = 'RESET_FINAL_SCORE';
