
export const FETCH_DEBIT_CARD_DATA = "FETCH_DEBIT_CARD_DATA";
export const ADD_NEW_DEBIT_CARD = 'ADD_NEW_DEBIT_CARD';
export const UPDATE_WEEKLY_SPENDING_LIMIT_DATA = 'UPDATE_WEEKLY_SPENDING_LIMIT_DATA';
export const UPDATE_FREEZE_CARD_DATA = 'UPDATE_FREEZE_CARD_DATA';
